
services:
  - type: web
    name: police-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DB_NAME
        value: police
    autoDeploy: true
    healthCheckPath: /api/health
